version: 3

dotenv:
  - .env.prod
  - .env

tasks:
  run:
    aliases: [default]
    cmd: python -u "./entry.py"
    interactive: true

  trace:
    cmd: python -u "./entry.py"
    interactive: true
    env:
      LOGURU_LEVEL: TRACE

  debug:
    cmd: python -u "./entry.py"
    interactive: true
    env:
      LOGURU_LEVEL: DEBUG
